project:
  type: website
  output-dir: docs

website:
  title: "Home"
  description: "Matemática aplicada · Optimización · Investigación de Operaciones · IA"
  navbar:
    background: dark
    left:
      - href: blog.qmd
        text: Blog
      - href: about.qmd
        text: Sobre mí
    right:
      - icon: github
        href: https://github.com/yosbijgolles
      - icon: linkedin
        href: https://linkedin.com/in/yosbijgolles
      - icon: youtube
        href: https://www.youtube.com/@yosbijgolles
  page-footer:
    center: "© 2026 Yosbi J. Golles — Inteligencia Especializada"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    lang: es
    language:
      title-block-author-single: "Autor"
    code-fold: false
    code-tools: false
