project:
  type: website
  output-dir: docs
  resources:
    - profile.jpg

website:
  title: "Inteligencia Especializada"
  navbar:
    left:
      - text: "Inicio"
        href: index.qmd
      - text: "Blog"
        href: blog.qmd
      - text: "Proyectos"
        href: projects.qmd
      - text: "Videos"
        href: videos.qmd
      - text: "Sobre m√≠"
        href: about.qmd
    right:
      - icon: github
        href: https://github.com/yosbijgolles
      - icon: youtube
        href: https://youtube.com/yosbijgolles

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    code-fold: false
    code-tools: false